* ukko
  :PROPERTIES:
  :CUSTOM_ID: ukko
  :END:

FIXME: description

** Installation

You have two options to install =ukko=.

*** Locally

    Premise: You have [[https://clojure.org/][Clojure]] and [[https://leiningen.org/][Leiningen]] installed.

    This is reasonable if you want to develop on =ukko= itself.

    1. Clone this repository.
    2. Run =lein bin=.

*** Using Docker

    Premise: You have [[https://www.docker.com/][Docker]] installed.

    Copy/paste this into your shell and you will have a =~/bin/ukko= file.

#+begin_src shell
cat >> ~/bin/ukko <<EOF
#!/bin/sh
docker run -it --rm -v \`pwd\`:/project twohundredok/ukko  /bin/bash -c "/bin/ukko \$@"
EOF

chmod +x ~/bin/ukko
#+end_src

** Usage

*** Config options

  - assets-path "assets"
  - data-path "data"
  - date-format-rfc-3339 "yyyy-MM-dd'T'HH:mm:ss'Z'"
  - date-format-rfc-822 "EEE, dd MMM yyyy HH:mm:ss Z"
  - site-path "site"
  - layouts-path "layouts"
  - target-path "public"
  - target-extension ".html"
  - format "passthrough"
  - layout ["post" "blog"]
  - priority 50

*** Metadata fields

**** scope (optional)

The default scope of

**** collection (optional)

Used to generate multiple files from one template.

Either an array (navigator), a map (cross product of navigators), or a
string (code that will be evaled).

**** format
**** layout
**** priority

** Options
   :PROPERTIES:
   :CUSTOM_ID: options
   :END:

FIXME: listing of options this app accepts.

** Examples
   :PROPERTIES:
   :CUSTOM_ID: examples
   :END:

...

*** Bugs
    :PROPERTIES:
    :CUSTOM_ID: bugs
    :END:

...

*** Any Other Sections
    :PROPERTIES:
    :CUSTOM_ID: any-other-sections
    :END:

*** That You Think
    :PROPERTIES:
    :CUSTOM_ID: that-you-think
    :END:

*** Might be Useful
    :PROPERTIES:
    :CUSTOM_ID: might-be-useful
    :END:
